tunnel: 6a9960c7-1fe2-4565-a583-6a0a3cd16d31
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: backend.discoverall.space
    service: http://app:3000
  - service: http_status:404
