CREATE TABLE IF NOT EXISTS websites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(500) NOT NULL,
    description TEXT,
    tags JSON DEFAULT ('[]'),
    views INT DEFAULT 0,
    likesMobile INT DEFAULT 0,
    dislikesMobile INT DEFAULT 0,
    likesDesktop INT DEFAULT 0,
    dislikesDesktop INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_url (url(255))
);
INSERT INTO websites (
        name,
        url,
        description,
        tags,
        views,
        likesMobile,
        dislikesMobile,
        likesDesktop,
        dislikesDesktop
    )
VALUES (
        'Hacker News',
        'https://news.ycombinator.com',
        'Social news website focusing on computer science and entrepreneurship',
        '["curated","sample"]',
        142,
        39,
        3,
        18,
        0
    ),
    (
        'Product Hunt',
        'https://www.producthunt.com',
        'Platform for sharing and discovering new products',
        '["curated","sample"]',
        122,
        29,
        2,
        15,
        0
    ),
    (
        'Unsplash',
        'https://unsplash.com',
        'Beautiful, free images gifted by the world''s most generous community of photographers',
        '["curated","sample"]',
        198,
        53,
        4,
        26,
        0
    ),
    (
        'skribbl.io',
        'https://skribbl.io/',
        'Free multiplayer drawing and guessing game',
        '["curated","sample"]',
        37,
        2,
        1000,
        1,
        0
    ),
    (
        'zeitgeist12345',
        'https://zeitgeist12345.github.io/',
        'The personal website of the creator of this project',
        '["curated","sample"]',
        48,
        3,
        0,
        2,
        1
    ),
    (
        'Sci-Hub',
        'https://sci-hub.se/',
        'Removing barriers in the way of science by providing free access to research papers',
        '["curated","sample"]',
        38,
        2,
        1000,
        1,
        0
    ),
    (
        'Library Genesis',
        'https://libgen.li/',
        'Massive digital library of books, articles, and media',
        '["curated","sample"]',
        52,
        4,
        0,
        1,
        1
    ),
    (
        'Internet Archive',
        'https://archive.org/',
        'Digital library of free & borrowable books, movies, music & Wayback Machine',
        '["curated","sample"]',
        57,
        4,
        0,
        5,
        0
    ),
    (
        'The Useless Web',
        'https://theuselessweb.com/',
        'Random fun and bizarre websites with one click',
        '["curated","sample"]',
        56,
        2,
        0,
        2,
        0
    ),
    (
        'Play Counter-Strike 1.6',
        'https://play-cs.com/',
        'Play classic CS 1.6 online without downloading',
        '["curated","sample"]',
        43,
        2,
        1000,
        3,
        0
    ),
    (
        'Overleaf',
        'https://www.overleaf.com/',
        'Online LaTeX editor with real-time collaboration',
        '["curated","sample"]',
        43,
        2,
        1000,
        1,
        0
    ),
    (
        'The Longest Blockchain',
        'https://cryptoservices.github.io/blockchain/consensus/2019/05/21/bitcoin-length-weight-confusion.html',
        'Interesting perspective on blockchain strength',
        '["curated","sample"]',
        64,
        2,
        0,
        2,
        0
    ),
    (
        'Bored Button',
        'https://www.boredbutton.com/',
        'Collection of random fun websites and games',
        '["curated","sample"]',
        45,
        2,
        1000,
        1,
        0
    ),
    (
        'Radio Garden',
        'http://radio.garden/',
        'Listen to live radio stations across the globe',
        '["curated","sample"]',
        45,
        2,
        1000,
        2,
        0
    ),
    (
        'Window Swap',
        'https://window-swap.com/',
        'See the view from someone else''s window around the world',
        '["curated","sample"]',
        51,
        2,
        1000,
        4,
        0
    ),
    (
        'The Pudding',
        'https://pudding.cool/',
        'Visual essays that explain ideas with data and visuals',
        '["curated","sample"]',
        69,
        2,
        0,
        3,
        0
    ),
    (
        'xkcd',
        'https://xkcd.com/',
        'A webcomic of romance, sarcasm, math, and language',
        '["curated","sample"]',
        57,
        12,
        1000,
        3,
        0
    ),
    (
        'Stellarium Web',
        'https://stellarium-web.org/',
        'Real-time 3D simulation of space with planetarium view',
        '["curated","sample"]',
        53,
        2,
        1000,
        1,
        0
    ),
    (
        'Patatap',
        'https://patatap.com',
        'Turn your keyboard into a sound machine with colorful animations',
        '["curated","sample"]',
        74,
        4,
        0,
        3,
        0
    ),
    (
        'Little Alchemy 2',
        'https://littlealchemy2.com',
        'Combine elements to discover new objects (e.g., Earth + Fire = Lava)',
        '["curated","sample"]',
        74,
        2,
        0,
        1,
        0
    ),
    (
        'Pointer Pointer',
        'https://pointerpointer.com',
        'Photos of people pointing at your cursor wherever you move it',
        '["curated","sample"]',
        70,
        2,
        0,
        2,
        1
    ),
    (
        'Ncase.me',
        'https://ncase.me',
        'Interactive simulations about trust and human behavior',
        '["curated","sample"]',
        75,
        2,
        0,
        1,
        0
    ),
    (
        'Connected Papers',
        'https://www.connectedpapers.com',
        'Visual tool to explore academic research connections',
        '["curated","sample"]',
        70,
        2,
        0,
        10,
        0
    ),
    (
        'Quick, Draw!',
        'https://quickdraw.withgoogle.com',
        'AI game that guesses your doodles',
        '["curated","sample"]',
        60,
        2,
        1000,
        1,
        0
    ),
    (
        'A Soft Murmur',
        'https://asoftmurmur.com',
        'Mix ambient sounds (rain, waves) for focus',
        '["curated","sample"]',
        61,
        2,
        1000,
        2,
        0
    ),
    (
        '10 Minute Mail',
        'https://10minutemail.com',
        'Disposable email for spam-free signups',
        '["curated","sample"]',
        61,
        2,
        1000,
        1,
        0
    ),
    (
        'The Deep Sea',
        'https://neal.fun/deep-sea',
        'Interactive dive into ocean depths with fascinating facts',
        '["curated","sample"]',
        63,
        2,
        1000,
        1,
        0
    ),
    (
        'Don''t Even Reply',
        'https://dontevenreply.com',
        'Hilarious fictional email exchanges',
        '["curated","sample"]',
        83,
        2,
        0,
        8,
        0
    ),
    (
        'Scream Into the Void',
        'https://screamintothevoid.com',
        'Type your frustrations and hear a scream',
        '["curated","sample"]',
        61,
        2,
        1000,
        1,
        1
    ),
    (
        'This Is Sand',
        'https://thisissand.com',
        'Digital sand art creator',
        '["curated","sample"]',
        67,
        2,
        1000,
        2,
        0
    ),
    (
        'DeepSeek',
        'https://www.deepseek.com/en',
        'AI research and development company',
        '["curated","sample"]',
        66,
        2,
        1000,
        1,
        0
    ),
    (
        'DeepSeek',
        'https://chat.deepseek.com/',
        'Cutting edge open weight open research LLM.',
        '["curated","sample"]',
        63,
        2,
        1000,
        2,
        0
    ),
    (
        'Al Jazeera',
        'https://www.aljazeera.com',
        'International news and current affairs network',
        '["curated","sample"]',
        86,
        7,
        0,
        4,
        0
    ),
    (
        'In depth flow of computers',
        'https://github.com/alex/what-happens-when',
        'An attempt to answer the age old interview question - What happens when you type google.com into your browser and press enter? This page explains how the computer systems work together.',
        '["curated","sample"]',
        89,
        2,
        0,
        5,
        0
    ),
    (
        'Software build systems',
        'https://bazel.build/basics',
        'The best guide on how software build systems work and their evolution. Bazel is the best build system by Google offering 0.5 second incremental build times using functional programming concepts.',
        '["curated","sample"]',
        81,
        2,
        0,
        4,
        1
    ),
    (
        'Examples website',
        'https://www.example.com',
        'Example website',
        '["beautiful","gorgeous"]',
        21,
        0,
        0,
        5,
        2
    ),
    (
        'google',
        'www.google.com',
        'Search engine.',
        '[]',
        22,
        0,
        0,
        11,
        3
    ),
    (
        'Yahoo',
        'www.yahoo.com',
        'Search engine.',
        '[]',
        19,
        0,
        0,
        10,
        4
    ),
    (
        'Sony',
        'sony.com',
        'Tech giant.',
        '[]',
        22,
        1,
        0,
        3,
        0
    ),
    (
        'twitte',
        'twitter.com',
        'twitter',
        '[]',
        19,
        0,
        0,
        9,
        5
    ),
    (
        'lg',
        'lg.com',
        'lg',
        '["wesome","wesome,gorgeous"]',
        21,
        0,
        0,
        1,
        0
    ),
    (
        'Canon',
        'canon.com',
        'Tech company.',
        '["cool","awesome","wow","beautiful"]',
        26,
        2,
        0,
        0,
        1
    ),
    (
        'Honda',
        'honda.com',
        'Hardware company.',
        '["brilliant","good","pretty","poetic"]',
        26,
        4,
        0,
        1,
        0
    ),
    (
        'Codeforces',
        'https://codeforces.com/problemset',
        'The top competitive programming platform.',
        '["code","learning","fun","poetic"]',
        21,
        0,
        0,
        2,
        0
    ),
    (
        'Interview Ready',
        'https://interviewready.io/learn/ai-engineering/who-is-this-course-for/course-intro',
        'Best backend engineering course.',
        '["learning","code","backend","course"]',
        24,
        0,
        0,
        5,
        2
    ),
    (
        'Rekhta famous shayaris',
        'https://www.rekhta.org/tags/famous-shayari/couplets',
        'Ponder and it might help clear blockers in the mind.',
        '["shayaris","cool","poetic","beautiful"]',
        18,
        1,
        0,
        3,
        0
    ),
    (
        'sci net.',
        'https://sci-net.xyz/',
        'Open scientific papers submitted by paper authors.',
        '["science","research","cool"]',
        13,
        0,
        0,
        1,
        0
    ),
    (
        'Project Euler',
        'https://projecteuler.net/',
        'Project Euler is a series of challenging mathematical/computer programming problems that will require more than just mathematical insights to solve. 
The motivation for starting Project Euler, and its continuation, is to provide a platform for the inquiring mind to delve into unfamiliar areas and learn new concepts in a fun and recreational context.',
        '["math","cs","coding"]',
        13,
        5,
        0,
        1,
        0
    ),
    (
        'BYD',
        'https://www.byd.com/',
        'Electric car company.',
        '["car","electric","company"]',
        15,
        2,
        0,
        2,
        0
    ),
    (
        'MediaTek',
        'https://www.mediatek.com/',
        'Silicon chips company.',
        '["silicon","chips","company"]',
        15,
        1,
        0,
        3,
        0
    ),
    (
        'MSI',
        'https://msi.com',
        'Computer motherboard company.',
        '["computer","motherboard","company"]',
        14,
        1,
        0,
        3,
        0
    ),
    (
        'Nissan',
        'https://www.nissan-global.com/EN/',
        'Car company',
        '["car","company"]',
        15,
        0,
        0,
        1,
        1
    ),
    (
        'YouTube',
        'https://m.youtube.com/feed/subscriptions',
        'The subscriptions feed does not have implicit personalized recommendations.',
        '["video","social","good","dynamic","regular","repeat"]',
        5,
        1,
        0,
        2,
        0
    ),
    (
        'High Scalability',
        'https://highscalability.com/',
        'System Design Blogs',
        '["user-submitted"]',
        6,
        0,
        0,
        2,
        0
    ),
    (
        'Compiler Explorer',
        'https://godbolt.org/',
        'Test different computer programming language compilers.',
        '["user-submitted"]',
        8,
        0,
        0,
        3,
        0
    ),
    (
        'Competitive Programmer''s Handbook',
        'https://github.com/pllk/cphb/',
        'Best competitive programming book.',
        '["user-submitted"]',
        4,
        0,
        0,
        1,
        0
    ),
    (
        'GeeksforGeeks',
        'https://www.geeksforgeeks.org/',
        'Computer Science learning platform.',
        '["user-submitted"]',
        6,
        0,
        0,
        1,
        0
    ),
    (
        'hashnode',
        'https://hashnode.com/featured',
        'Developer blog platform.',
        '["user-submitted"]',
        7,
        1,
        0,
        1,
        0
    ),
    (
        'The DeepSeek Series: A Technical Overview',
        'https://martinfowler.com/articles/deepseek-papers.html',
        'This article provides an overview of the DeepSeek papers, highlighting three main arcs in this research: a focus on improving cost and memory efficiency, the use of HPC Co-Design to train large models on limited hardware, and the development of emergent reasoning from large-scale reinforcement learning.',
        '["user-submitted"]',
        9,
        2,
        0,
        1,
        0
    ),
    (
        'Andher Nagri Chaupat Raja : Bharatendu Harishchandra',
        'https://hindi-kavita.com/HindiAndherNagriBharatenduHarishchandra.php',
        'Short play on the British rule in India',
        '["user-submitted"]',
        7,
        1,
        0,
        2,
        0
    ),
    (
        'Fatiha ka tarika',
        'https://namazein.com/fatiha-ka-tarika/',
        'How to do fatiha follow through guide.',
        '["user-submitted"]',
        7,
        1,
        0,
        2,
        0
    ),
    (
        'Muslim Prayer - How to perform 2 Raka''at (2 Units) of prayer',
        'https://www.youtube.com/watch?v=jxLsiOflofk',
        'Muslim Prayer - How to perform 2 Raka''at (2 Units) of prayer to help in praying Jumma farz namaz.',
        '["user-submitted"]',
        5,
        3,
        0,
        1,
        0
    ),
    (
        'draw.io',
        'https://app.diagrams.net/#',
        'Diagram making software which includes UML diagrams in software engineering.',
        '["user-submitted"]',
        6,
        0,
        0,
        4,
        0
    ),
    (
        '4chan',
        'https://4chan.org/',
        'Free speech social media platform.',
        '["user-submitted"]',
        9,
        1,
        0,
        1,
        0
    ),
    (
        'Blind',
        'https://www.teamblind.com/',
        'Social media.',
        '["social","media"]',
        4,
        0,
        0,
        0,
        0
    ),
    (
        'Blind recent sort',
        'https://www.teamblind.com/?sort=id',
        'Social media.',
        '["social","media"]',
        2,
        1,
        0,
        0,
        0
    ),
    (
        'Group trivia game',
        'https://crowdparty.app/',
        'Group online trivia game.',
        '["user-submitted"]',
        0,
        0,
        0,
        0,
        0
    ),
    (
        'Group puzzle game',
        'https://codenames.game/',
        'Group online puzzle game.',
        '["user-submitted"]',
        0,
        0,
        0,
        0,
        0
    ),
    (
        'Moj',
        'https://mojapp.in',
        'TikTok alternative.',
        '["tiktok","moj","social","media","socialmedia","app"]',
        0,
        0,
        0,
        0,
        0
    ),
    (
        'Oppo',
        'https://www.oppo.com',
        'Mobile phone company.',
        '["mobile","mobile phone","company","mobilephonecompany","poetic"]',
        0,
        0,
        0,
        0,
        0
    ),
    (
        'OnePlus',
        'https://www.oneplus.com',
        'Phone company',
        '["phone","phonecompany","mobilephonecompany","poetic"]',
        0,
        0,
        0,
        0,
        0
    ) ON DUPLICATE KEY
UPDATE id = id;