CREATE TABLE IF NOT EXISTS websites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(500) NOT NULL,
    description TEXT,
    tags JSON DEFAULT ('[]'),
    views INT DEFAULT 0,
    likesMobile INT DEFAULT 0,
    dislikesMobile INT DEFAULT 0,
    likesDesktop INT DEFAULT 0,
    dislikesDesktop INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_url (url(255))
);
INSERT INTO websites (
        name,
        url,
        description,
        tags,
        views,
        likesMobile,
        dislikesMobile,
        likesDesktop,
        dislikesDesktop
    )
VALUES (
        'Hacker News',
        'https://news.ycombinator.com',
        'Social news website focusing on computer science and entrepreneurship',
        '["curated","sample"]',
        120,
        35,
        3,
        18,
        0
    ),
    (
        'Product Hunt',
        'https://www.producthunt.com',
        'Platform for sharing and discovering new products',
        '["curated","sample"]',
        95,
        28,
        2,
        15,
        0
    ),
    (
        'Unsplash',
        'https://unsplash.com',
        'Beautiful, free images gifted by the world''s most generous community of photographers',
        '["curated","sample"]',
        180,
        52,
        4,
        25,
        0
    ),
    (
        'skribbl.io',
        'https://skribbl.io/',
        'Free multiplayer drawing and guessing game',
        '["curated","sample"]',
        30,
        2,
        1000,
        1,
        0
    ),
    (
        'zeitgeist12345',
        'https://zeitgeist12345.github.io/',
        'The personal website of the creator of this project',
        '["curated","sample"]',
        31,
        2,
        0,
        1,
        0
    ),
    (
        'Sci-Hub',
        'https://sci-hub.se/',
        'Removing barriers in the way of science by providing free access to research papers',
        '["curated","sample"]',
        32,
        2,
        1000,
        1,
        0
    ),
    (
        'Library Genesis',
        'https://libgen.li/',
        'Massive digital library of books, articles, and media',
        '["curated","sample"]',
        33,
        2,
        0,
        1,
        0
    ),
    (
        'Internet Archive',
        'https://archive.org/',
        'Digital library of free & borrowable books, movies, music & Wayback Machine',
        '["curated","sample"]',
        34,
        2,
        0,
        1,
        0
    ),
    (
        'The Useless Web',
        'https://theuselessweb.com/',
        'Random fun and bizarre websites with one click',
        '["curated","sample"]',
        35,
        2,
        0,
        1,
        0
    ),
    (
        'Play Counter-Strike 1.6',
        'https://play-cs.com/',
        'Play classic CS 1.6 online without downloading',
        '["curated","sample"]',
        36,
        2,
        1000,
        1,
        0
    ),
    (
        'Overleaf',
        'https://www.overleaf.com/',
        'Online LaTeX editor with real-time collaboration',
        '["curated","sample"]',
        39,
        2,
        1000,
        1,
        0
    ),
    (
        'The Longest Blockchain',
        'https://cryptoservices.github.io/blockchain/consensus/2019/05/21/bitcoin-length-weight-confusion.html',
        'Interesting perspective on blockchain strength',
        '["curated","sample"]',
        40,
        2,
        0,
        1,
        0
    ),
    (
        'Bored Button',
        'https://www.boredbutton.com/',
        'Collection of random fun websites and games',
        '["curated","sample"]',
        41,
        2,
        1000,
        1,
        0
    ),
    (
        'Radio Garden',
        'http://radio.garden/',
        'Listen to live radio stations across the globe',
        '["curated","sample"]',
        42,
        2,
        1000,
        1,
        0
    ),
    (
        'Window Swap',
        'https://window-swap.com/',
        'See the view from someone else''s window around the world',
        '["curated","sample"]',
        43,
        2,
        1000,
        1,
        0
    ),
    (
        'The Pudding',
        'https://pudding.cool/',
        'Visual essays that explain ideas with data and visuals',
        '["curated","sample"]',
        44,
        2,
        0,
        1,
        0
    ),
    (
        'xkcd',
        'https://xkcd.com/',
        'A webcomic of romance, sarcasm, math, and language',
        '["curated","sample"]',
        45,
        12,
        0,
        1,
        0
    ),
    (
        'Stellarium Web',
        'https://stellarium-web.org/',
        'Real-time 3D simulation of space with planetarium view',
        '["curated","sample"]',
        46,
        2,
        1000,
        1,
        0
    ),
    (
        'Patatap',
        'https://patatap.com',
        'Turn your keyboard into a sound machine with colorful animations',
        '["curated","sample"]',
        47,
        2,
        0,
        1,
        0
    ),
    (
        'Little Alchemy 2',
        'https://littlealchemy2.com',
        'Combine elements to discover new objects (e.g., Earth + Fire = Lava)',
        '["curated","sample"]',
        48,
        2,
        0,
        1,
        0
    ),
    (
        'Pointer Pointer',
        'https://pointerpointer.com',
        'Photos of people pointing at your cursor wherever you move it',
        '["curated","sample"]',
        49,
        2,
        0,
        1,
        0
    ),
    (
        'Ncase.me',
        'https://ncase.me',
        'Interactive simulations about trust and human behavior',
        '["curated","sample"]',
        50,
        2,
        0,
        1,
        0
    ),
    (
        'Connected Papers',
        'https://www.connectedpapers.com',
        'Visual tool to explore academic research connections',
        '["curated","sample"]',
        51,
        2,
        0,
        1,
        0
    ),
    (
        'Quick, Draw!',
        'https://quickdraw.withgoogle.com',
        'AI game that guesses your doodles',
        '["curated","sample"]',
        52,
        2,
        1000,
        1,
        0
    ),
    (
        'A Soft Murmur',
        'https://asoftmurmur.com',
        'Mix ambient sounds (rain, waves) for focus',
        '["curated","sample"]',
        53,
        2,
        1000,
        1,
        0
    ),
    (
        '10 Minute Mail',
        'https://10minutemail.com',
        'Disposable email for spam-free signups',
        '["curated","sample"]',
        54,
        2,
        1000,
        1,
        0
    ),
    (
        'The Deep Sea',
        'https://neal.fun/deep-sea',
        'Interactive dive into ocean depths with fascinating facts',
        '["curated","sample"]',
        55,
        2,
        1000,
        1,
        0
    ),
    (
        'Don''t Even Reply',
        'https://dontevenreply.com',
        'Hilarious fictional email exchanges',
        '["curated","sample"]',
        56,
        2,
        0,
        1,
        0
    ),
    (
        'Scream Into the Void',
        'https://screamintothevoid.com',
        'Type your frustrations and hear a scream',
        '["curated","sample"]',
        57,
        2,
        1000,
        1,
        0
    ),
    (
        'This Is Sand',
        'https://thisissand.com',
        'Digital sand art creator',
        '["curated","sample"]',
        58,
        2,
        1000,
        1,
        0
    ),
    (
        'DeepSeek',
        'https://www.deepseek.com/en',
        'AI research and development company',
        '["curated","sample"]',
        59,
        2,
        1000,
        1,
        0
    ),
    (
        'DeepSeek',
        'https://chat.deepseek.com/',
        'Cutting edge open weight open research LLM.',
        '["curated","sample"]',
        59,
        2,
        1000,
        1,
        0
    ),
    (
        'Al Jazeera',
        'https://www.aljazeera.com',
        'International news and current affairs network',
        '["curated","sample"]',
        60,
        2,
        0,
        1,
        0
    ),
    (
        'In depth flow of computers',
        'https://github.com/alex/what-happens-when',
        'An attempt to answer the age old interview question - What happens when you type google.com into your browser and press enter? This page explains how the computer systems work together.',
        '["curated","sample"]',
        61,
        2,
        0,
        1,
        0
    ),
    (
        'Software build systems',
        'https://bazel.build/basics',
        'The best guide on how software build systems work and their evolution. Bazel is the best build system by Google offering 0.5 second incremental build times using functional programming concepts.',
        '["curated","sample"]',
        62,
        2,
        0,
        1,
        0
    ) ON DUPLICATE KEY
UPDATE id = id;