CREATE TABLE IF NOT EXISTS links (
    url VARCHAR(500) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    tags JSON DEFAULT (JSON_ARRAY()),
    views INT DEFAULT 0,
    likesMobile INT DEFAULT 0,
    dislikesMobile INT DEFAULT 0,
    likesDesktop INT DEFAULT 0,
    dislikesDesktop INT DEFAULT 0,
    reviewStatus INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO links (
        name,
        url,
        description,
        tags,
        views,
        likesMobile,
        dislikesMobile,
        likesDesktop,
        dislikesDesktop,
        reviewStatus
    )
VALUES (
        '10 Minute Mail',
        'https://10minutemail.com/',
        'Disposable email for spam-free signups',
        JSON_ARRAY('curated', 'sample'),
        64,
        2,
        1000,
        1,
        0,
        1
    ),
    (
        '12 Rules for Life - Jordan Bernt Peterson',
        'https://www.penguinrandomhouse.co.za/sites/penguinbooks.co.za/files/Extract_12%20Rules%20for%20Life.PDF',
        'The bridge between European ideas and Islam. Beyond Order: 12 More Rules for Life is also a required read after this book. Jordan Bernt Peterson almost reached Islam with pure logic which is remarkable. The difference can be seen in his Rule 8 of "tell the truth, or atleast don''t lie" and the holy Quran''s ''do not mix truth with falsehood, nor knowingly conceal the truth'' - Surah Al-Baqarah (2:42). The Quran is much more strict and rewarding.',
        JSON_ARRAY('book', 'learning', '12rulesforlife'),
        22,
        2,
        0,
        0,
        0,
        1
    ),
    (
        '4chan',
        'https://4chan.org/',
        'Free speech social media platform.',
        JSON_ARRAY('user-submitted'),
        46,
        1,
        0,
        2,
        0,
        1
    ),
    (
        'A Soft Murmur',
        'https://asoftmurmur.com/',
        'Mix ambient sounds (rain, waves) for focus',
        JSON_ARRAY('curated', 'sample'),
        65,
        2,
        1000,
        2,
        0,
        1
    ),
    (
        'abirusabil123',
        'https://abirusabil123.github.io/',
        'The personal link of the creator of this project',
        JSON_ARRAY('curated', 'sample'),
        87,
        4,
        0,
        2,
        1,
        1
    ),
    (
        'Al Jazeera',
        'https://www.aljazeera.com/',
        'International news and current affairs network',
        JSON_ARRAY('curated', 'sample'),
        122,
        8,
        0,
        4,
        0,
        1
    ),
    (
        'Aljazeera flips',
        'https://www.aljazeera.com/#flips',
        'Aljazeera flips',
        JSON_ARRAY('aljazeeraflips', 'aljazeera', 'flips', 'learning'),
        30,
        1,
        0,
        0,
        0,
        1
    ),
    (
        'Aljazeera flips',
        'https://www.aljazeera.com/#flips-6386609485112',
        'Short clips from Aljazeera.',
        JSON_ARRAY('aljazeera', 'flips', 'learning'),
        9,
        1,
        0,
        0,
        0,
        1
    ),
    (
        'Aljazeera flips',
        'https://www.aljazeera.com/#flips-6386599316112',
        'Short clips from Aljazeera.',
        JSON_ARRAY('aljazeera', 'flips', 'learning'),
        17,
        1,
        0,
        0,
        0,
        1
    ),
    (
        'Andher Nagri Chaupat Raja : Bharatendu Harishchandra',
        'https://hindi-kavita.com/HindiAndherNagriBharatenduHarishchandra.php',
        'Short play on the British rule in India',
        JSON_ARRAY('user-submitted'),
        49,
        2,
        0,
        3,
        0,
        1
    ),
    (
        'Anna''s archive',
        'https://annas-archive.se/',
        'Open library.',
        JSON_ARRAY('open', 'library', 'books'),
        27,
        1,
        0,
        1,
        1,
        1
    ),
    (
        'Anna''s Archive',
        'https://annas-archive.org/',
        'Open library',
        JSON_ARRAY('open', 'library', 'learning'),
        7,
        0,
        0,
        0,
        0,
        1
    ),
    (
        'Blind',
        'https://www.teamblind.com/',
        'Social media.',
        JSON_ARRAY('social', 'media'),
        40,
        0,
        0,
        0,
        0,
        1
    ),
    (
        'Blind recent sort',
        'https://www.teamblind.com/?sort=id',
        'Social media.',
        JSON_ARRAY('social', 'media'),
        45,
        3,
        0,
        0,
        0,
        1
    ),
    (
        'Bored Button',
        'https://www.boredbutton.com/',
        'Collection of random fun links and games',
        JSON_ARRAY('curated', 'sample'),
        49,
        2,
        1000,
        1,
        0,
        1
    ),
    (
        'BYD',
        'https://www.byd.com/',
        'Electric car company.',
        JSON_ARRAY('car', 'electric', 'company'),
        46,
        5,
        0,
        2,
        0,
        1
    ),
    (
        'Canon',
        'https://canon.com/',
        'Tech company.',
        JSON_ARRAY('cool', 'awesome', 'wow', 'beautiful'),
        38,
        3,
        1000,
        3,
        1002,
        1
    ),
    (
        'Codeforces',
        'https://codeforces.com/problemset',
        'The top competitive programming platform.',
        JSON_ARRAY('code', 'learning', 'fun', 'poetic'),
        61,
        0,
        0,
        2,
        0,
        1
    ),
    (
        'Competitive Programmer''s Handbook',
        'https://github.com/pllk/cphb/',
        'Best competitive programming book.',
        JSON_ARRAY('user-submitted'),
        11,
        0,
        1000,
        2,
        0,
        1
    ),
    (
        'Compiler Explorer',
        'https://godbolt.org/',
        'Test different computer programming language compilers.',
        JSON_ARRAY('user-submitted'),
        15,
        0,
        1000,
        4,
        0,
        1
    ),
    (
        'Connected Papers',
        'https://www.connectedpapers.com/',
        'Visual tool to explore academic research connections',
        JSON_ARRAY('curated', 'sample'),
        78,
        2,
        1000,
        10,
        0,
        1
    ),
    (
        'DeepSeek',
        'https://chat.deepseek.com/',
        'Cutting edge open weight open research LLM.',
        JSON_ARRAY('curated', 'sample'),
        69,
        2,
        1000,
        2,
        0,
        1
    ),
    (
        'DeepSeek',
        'https://www.deepseek.com/en',
        'AI research and development company',
        JSON_ARRAY('curated', 'sample'),
        73,
        2,
        1000,
        1,
        1,
        1
    ),
    (
        'Don''t Even Reply',
        'https://dontevenreply.com/',
        'Hilarious fictional email exchanges',
        JSON_ARRAY('curated', 'sample'),
        88,
        2,
        1000,
        9,
        0,
        1
    ),
    (
        'draw.io',
        'https://app.diagrams.net/',
        'Diagram making software which includes UML diagrams in software engineering.',
        JSON_ARRAY('user-submitted'),
        10,
        0,
        1000,
        7,
        0,
        1
    ),
    (
        'Examples link',
        'https://www.example.com/',
        'Example link',
        JSON_ARRAY('beautiful', 'gorgeous'),
        25,
        0,
        2000,
        6,
        1004,
        1
    ),
    (
        'Fatiha ka tarika',
        'https://namazein.com/fatiha-ka-tarika/',
        'How to do fatiha follow through guide.',
        JSON_ARRAY('user-submitted'),
        39,
        1,
        0,
        2,
        0,
        1
    ),
    (
        'GeeksforGeeks',
        'https://www.geeksforgeeks.org/',
        'Computer Science learning platform.',
        JSON_ARRAY('user-submitted'),
        35,
        0,
        0,
        1,
        0,
        1
    ),
    (
        'Group puzzle game',
        'https://codenames.game/',
        'Group online puzzle game.',
        JSON_ARRAY('user-submitted'),
        2,
        0,
        1000,
        0,
        0,
        1
    ),
    (
        'Group trivia game',
        'https://crowdparty.app/',
        'Group online trivia game.',
        JSON_ARRAY('user-submitted'),
        5,
        0,
        1000,
        1,
        0,
        1
    ),
    (
        'Hacker News',
        'https://news.ycombinator.com/',
        'Social news link focusing on computer science and entrepreneurship',
        JSON_ARRAY('curated', 'sample'),
        184,
        41,
        3,
        18,
        0,
        1
    ),
    (
        'hashnode',
        'https://hashnode.com/featured',
        'Developer blog platform.',
        JSON_ARRAY('user-submitted'),
        35,
        4,
        0,
        1,
        0,
        1
    ),
    (
        'Hashnode recent',
        'https://hashnode.com/recent',
        'Blogging platform.',
        JSON_ARRAY('tech', 'blog', 'learning'),
        20,
        0,
        0,
        0,
        0,
        1
    ),
    (
        'High Scalability',
        'https://highscalability.com/',
        'System Design Blogs',
        JSON_ARRAY('user-submitted'),
        40,
        1,
        0,
        2,
        0,
        1
    ),
    (
        'Honda',
        'https://honda.com/',
        'Hardware company.',
        JSON_ARRAY('brilliant', 'good', 'pretty', 'poetic'),
        56,
        5,
        0,
        1,
        0,
        1
    ),
    (
        'How hate drove a Muslim flower-seller to death in a Maharashtra village',
        'https://www.newslaundry.com/2025/11/10/how-hate-drove-a-muslim-flower-seller-to-death-in-a-maharashtra-village',
        'Intolerance news.',
        JSON_ARRAY('learning', 'news'),
        0,
        0,
        0,
        0,
        0,
        1
    ),
    (
        'In depth flow of computers',
        'https://github.com/alex/what-happens-when',
        'An attempt to answer the age old interview question - What happens when you type google.com into your browser and press enter? This page explains how the computer systems work together.',
        JSON_ARRAY('curated', 'sample'),
        94,
        2,
        1000,
        5,
        0,
        1
    ),
    (
        'Internet Archive',
        'https://archive.org/',
        'Digital library of free & borrowable books, movies, music & Wayback Machine',
        JSON_ARRAY('curated', 'sample'),
        63,
        4,
        1000,
        5,
        0,
        1
    ),
    (
        'Interview Ready',
        'https://interviewready.io/learn/ai-engineering/who-is-this-course-for/course-intro',
        'Best backend engineering course.',
        JSON_ARRAY('learning', 'code', 'backend', 'course'),
        28,
        0,
        1000,
        5,
        2,
        1
    ),
    (
        'Interview Ready - System Design',
        'https://interviewready.io/learn/system-design-course/how-do-i-use-this-course/what-do-we-offer?tab=chapters',
        'Best System Design course.',
        JSON_ARRAY('systemdesign', 'course', 'learning'),
        6,
        0,
        1001,
        1,
        0,
        1
    ),
    (
        'Kaggle',
        'https://www.kaggle.com/',
        'Participate in AI competitions.',
        JSON_ARRAY('ai', 'participate', 'compete', 'learning'),
        14,
        0,
        2002,
        1,
        0,
        1
    ),
    (
        'lg',
        'https://lg.com/',
        'lg',
        JSON_ARRAY('wesome', 'wesome,gorgeous'),
        57,
        3,
        0,
        1,
        0,
        1
    ),
    (
        'Library Genesis',
        'https://libgen.li/',
        'Massive digital library of books, articles, and media',
        JSON_ARRAY('curated', 'sample'),
        65,
        4,
        1000,
        2,
        1,
        1
    ),
    (
        'Linux Kernel Explorer',
        'https://reverser.dev/linux-kernel-explorer',
        'A portal to study the Linux Kernel.',
        JSON_ARRAY('linux', 'kernel'),
        3,
        0,
        1001,
        0,
        0,
        1
    ),
    (
        'Little Alchemy 2',
        'https://littlealchemy2.com/',
        'Combine elements to discover new objects (e.g., Earth + Fire = Lava)',
        JSON_ARRAY('curated', 'sample'),
        121,
        2,
        0,
        1,
        0,
        1
    ),
    (
        'LLM Embeddings Explained',
        'https://huggingface.co/spaces/hesamation/primer-llm-embedding',
        'LLM Embeddings Explained: A Visual and Intuitive Guide',
        JSON_ARRAY('llm', 'ai', 'explained'),
        5,
        0,
        1001,
        1,
        0,
        1
    ),
    (
        'MediaTek',
        'https://www.mediatek.com/',
        'Silicon chips company.',
        JSON_ARRAY('silicon', 'chips', 'company'),
        41,
        2,
        0,
        4,
        0,
        1
    ),
    (
        'Moj',
        'https://mojapp.in/',
        'TikTok alternative.',
        JSON_ARRAY('tiktok', 'moj', 'social', 'media', 'socialmedia', 'app'),
        4,
        0,
        2000,
        1,
        1001,
        1
    ),
    (
        'MSI',
        'https://msi.com/',
        'Computer motherboard company.',
        JSON_ARRAY('computer', 'motherboard', 'company'),
        47,
        1,
        0,
        3,
        0,
        1
    ),
    (
        'Muslim Prayer - How to perform 2 Raka''at (2 Units) of prayer',
        'https://www.youtube.com/watch?v=jxLsiOflofk',
        'Muslim Prayer - How to perform 2 Raka''at (2 Units) of prayer to help in praying Jumma farz namaz.',
        JSON_ARRAY('user-submitted'),
        45,
        7,
        0,
        2,
        0,
        1
    ),
    (
        'Ncase.me',
        'https://ncase.me/',
        'Interactive simulations about trust and human behavior',
        JSON_ARRAY('curated', 'sample'),
        113,
        3,
        0,
        1,
        0,
        1
    ),
    (
        'Nissan',
        'https://www.nissan-global.com/EN/',
        'Car company',
        JSON_ARRAY('car', 'company'),
        50,
        2,
        0,
        1,
        1,
        1
    ),
    (
        'OnePlus',
        'https://www.oneplus.com/',
        'Phone company',
        JSON_ARRAY('phone', 'phonecompany', 'mobilephonecompany', 'poetic'),
        36,
        1,
        0,
        0,
        0,
        1
    ),
    (
        'Oppo',
        'https://www.oppo.com/',
        'Mobile phone company.',
        JSON_ARRAY('mobile', 'mobile phone', 'company', 'mobilephonecompany', 'poetic'),
        37,
        0,
        2,
        2,
        0,
        1
    ),
    (
        'Overleaf',
        'https://www.overleaf.com/',
        'Online LaTeX editor with real-time collaboration',
        JSON_ARRAY('curated', 'sample'),
        48,
        2,
        1000,
        2,
        0,
        1
    ),
    (
        'Pal Pal',
        'https://www.youtube.com/watch?v=8of5w7RgcTc',
        'Contemplative popular music in Urdu.',
        JSON_ARRAY('urdu', 'music'),
        26,
        1,
        0,
        0,
        0,
        1
    ),
    (
        'Patatap',
        'https://patatap.com/',
        'Turn your keyboard into a sound machine with colorful animations',
        JSON_ARRAY('curated', 'sample'),
        112,
        4,
        0,
        3,
        0,
        1
    ),
    (
        'Play Counter-Strike 1.6',
        'https://play-cs.com/',
        'Play classic CS 1.6 online without downloading',
        JSON_ARRAY('curated', 'sample'),
        49,
        2,
        1000,
        3,
        0,
        1
    ),
    (
        'Pointer Pointer',
        'https://pointerpointer.com/',
        'Photos of people pointing at your cursor wherever you move it',
        JSON_ARRAY('curated', 'sample'),
        106,
        4,
        0,
        2,
        1,
        1
    ),
    (
        'Product Hunt',
        'https://www.producthunt.com/',
        'Platform for sharing and discovering new products',
        JSON_ARRAY('curated', 'sample'),
        157,
        30,
        3,
        16,
        0,
        1
    ),
    (
        'Project Euler',
        'https://projecteuler.net/',
        'Project Euler is a series of challenging mathematical/computer programming problems that will require more than just mathematical insights to solve. The motivation for starting Project Euler, and its continuation, is to provide a platform for the inquiring mind to delve into unfamiliar areas and learn new concepts in a fun and recreational context.',
        JSON_ARRAY('math', 'cs', 'coding'),
        46,
        5,
        0,
        1,
        0,
        1
    ),
    (
        'Quick, Draw!',
        'https://quickdraw.withgoogle.com/',
        'AI game that guesses your doodles',
        JSON_ARRAY('curated', 'sample'),
        62,
        2,
        1000,
        1,
        0,
        1
    ),
    (
        'Radio Garden',
        'http://radio.garden/',
        'Listen to live radio stations across the globe',
        JSON_ARRAY('curated', 'sample'),
        50,
        2,
        1000,
        3,
        0,
        1
    ),
    (
        'Rekhta famous shayaris',
        'https://www.rekhta.org/tags/famous-shayari/couplets',
        'Ponder and it might help clear blockers in the mind.',
        JSON_ARRAY('shayaris', 'cool', 'poetic', 'beautiful'),
        54,
        1,
        0,
        3,
        0,
        1
    ),
    (
        'sci net.',
        'https://sci-net.xyz/',
        'Open scientific papers submitted by paper authors.',
        JSON_ARRAY('science', 'research', 'cool'),
        42,
        2,
        1000,
        1,
        0,
        1
    ),
    (
        'Sci-Hub',
        'https://sci-hub.se/',
        'Removing barriers in the way of science by providing free access to research papers',
        JSON_ARRAY('curated', 'sample'),
        42,
        2,
        1000,
        1,
        0,
        1
    ),
    (
        'Scream Into the Void',
        'https://screamintothevoid.com/',
        'Type your frustrations and hear a scream',
        JSON_ARRAY('curated', 'sample'),
        66,
        2,
        1000,
        1,
        1,
        1
    ),
    (
        'skribbl.io',
        'https://skribbl.io/',
        'Free multiplayer drawing and guessing game',
        JSON_ARRAY('curated', 'sample'),
        45,
        2,
        1000,
        1,
        0,
        1
    ),
    (
        'Software build systems',
        'https://bazel.build/basics',
        'The best guide on how software build systems work and their evolution. Bazel is the best build system by Google offering 0.5 second incremental build times using functional programming concepts.',
        JSON_ARRAY('curated', 'sample'),
        119,
        2,
        0,
        5,
        1,
        1
    ),
    (
        'Sony',
        'https://sony.com/',
        'Tech giant.',
        JSON_ARRAY(),
        31,
        1,
        1000,
        5,
        0,
        1
    ),
    (
        'Stellarium Web',
        'https://stellarium-web.org/',
        'Real-time 3D simulation of space with planetarium view',
        JSON_ARRAY('curated', 'sample'),
        58,
        2,
        1000,
        1,
        0,
        1
    ),
    (
        'Tails',
        'https://tails.net/',
        'Secure OS.',
        JSON_ARRAY('secure', 'os', 'privacy'),
        6,
        3,
        1002,
        6,
        0,
        1
    ),
    (
        'The Deep Sea',
        'https://neal.fun/deep-sea',
        'Interactive dive into ocean depths with fascinating facts',
        JSON_ARRAY('curated', 'sample'),
        72,
        2,
        1000,
        1,
        0,
        1
    ),
    (
        'The DeepSeek Series: A Technical Overview',
        'https://martinfowler.com/articles/deepseek-papers.html',
        'This article provides an overview of the DeepSeek papers, highlighting three main arcs in this research: a focus on improving cost and memory efficiency, the use of HPC Co-Design to train large models on limited hardware, and the development of emergent reasoning from large-scale reinforcement learning.',
        JSON_ARRAY('user-submitted'),
        32,
        2,
        1000,
        1,
        0,
        1
    ),
    (
        'The Longest Blockchain',
        'https://cryptoservices.github.io/blockchain/consensus/2019/05/21/bitcoin-length-weight-confusion.html',
        'Interesting perspective on blockchain strength',
        JSON_ARRAY('curated', 'sample'),
        68,
        2,
        1000,
        3,
        0,
        1
    ),
    (
        'The Pudding',
        'https://pudding.cool/',
        'Visual essays that explain ideas with data and visuals',
        JSON_ARRAY('curated', 'sample'),
        109,
        2,
        0,
        3,
        0,
        1
    ),
    (
        'The Useless Web',
        'https://theuselessweb.com/',
        'Random fun and bizarre links with one click',
        JSON_ARRAY('curated', 'sample'),
        100,
        3,
        1000,
        3,
        0,
        1
    ),
    (
        'This Is Sand',
        'https://thisissand.com/',
        'Digital sand art creator',
        JSON_ARRAY('curated', 'sample'),
        73,
        2,
        1000,
        3,
        0,
        1
    ),
    (
        'twitter',
        'https://twitter.com/',
        'twitter',
        JSON_ARRAY(),
        23,
        0,
        2000,
        10,
        1007,
        1
    ),
    (
        'Unsplash',
        'https://unsplash.com/',
        'Beautiful, free images gifted by the world''s most generous community of photographers',
        JSON_ARRAY('curated', 'sample'),
        235,
        54,
        4,
        26,
        0,
        1
    ),
    (
        'Window Swap',
        'https://window-swap.com/',
        'See the view from someone else''s window around the world',
        JSON_ARRAY('curated', 'sample'),
        53,
        2,
        1000,
        4,
        0,
        1
    ),
    (
        'xkcd',
        'https://xkcd.com/',
        'A webcomic of romance, sarcasm, math, and language',
        JSON_ARRAY('curated', 'sample'),
        62,
        12,
        6000,
        3,
        0,
        1
    ),
    (
        'YouTube',
        'https://m.youtube.com/feed/subscriptions',
        'The subscriptions feed does not have implicit personalized recommendations.',
        JSON_ARRAY('video', 'social', 'good', 'dynamic', 'regular', 'repeat'),
        41,
        2,
        0,
        4,
        1,
        1
    ) ON DUPLICATE KEY
UPDATE url = url;