version: "3.8"

services:
  # Node.js backend
  app:
    build: ./backend
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # MySQL database
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:2025.8.1
    restart: unless-stopped
    depends_on:
      - app
    command: tunnel --no-autoupdate run --config /etc/cloudflared/config.yml
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - ./cloudflared/6a9960c7-1fe2-4565-a583-6a0a3cd16d31.json:/etc/cloudflared/credentials.json:ro

volumes:
  mysql_data:
